[project]
name = "whole-body-estimators"
# As this version is currently ignored, we do not
# waste effort in mantain it in synch with the value
# specified in CMakeLists.txt
version = "0.0.0"
description = "YARP devices that implement estimators for humanoid robots."
authors = ["Silvio Traversaro <silvio@traversaro.it>"]
channels = ["conda-forge","robotology"]
platforms = ["linux-64", "win-64", "osx-64"]

# Workaround until https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9200
# is released

[activation]
scripts = ["pixi_activation.sh"]

[target.win-64.activation]
scripts = ["pixi_activation.bat"]


[tasks]

download_deps = {cmd = "echo Download all deps && mkdir -p ./.pixi_colcon_ws/src && vcs import --input ./pixi_source_deps.yaml ./.pixi_colcon_ws/src"}
install_deps = {cmd = "echo Install all deps && cd .pixi_colcon_ws && colcon build --metas ../pixi_source_deps_options.meta --event-handlers console_direct+ --merge-install --install-base $CMAKE_INSTALL_PREFIX"}

configure = { cmd = [
    "cmake",
    "-DCMAKE_BUILD_TYPE=Release",
    "-DCMAKE_INSTALL_PREFIX=$CMAKE_INSTALL_PREFIX",
    "-DBUILD_TESTING:BOOL=ON",
    # Use the cross-platform Ninja generator
    "-G",
    "Ninja",
    # The source is in the root directory
    "-S",
    ".",
    # We wanna build in the .build directory
    "-B",
    ".build",
]}

build = { cmd = "cmake --build .build --config Release", depends_on = ["configure"] }
test = { cmd = "ctest --test-dir .build --build-config Release --output-on-failure", depends_on = ["build"] }
install = { cmd = ["cmake", "--install", ".build", "--config", "Release"], depends_on = ["build"] }
uninstall = { cmd = ["cmake", "--build", ".build", "--target", "uninstall"]}


[dependencies]
c-compiler = "*"
cxx-compiler = "*"
ninja = "*"
cmake = "*"
make  = "*"
pkg-config = "*"
eigen = "*"
# Requires https://github.com/robotology/idyntree/pull/1178
idyntree = ">=12.2.0"
# YARP from source dependencies (used only when compiling idyntree from source)
ace = "*"
ycm-cmake-modules = "*"
catch2 = "*"
tinyxml = "*"
# iDynTree deps from source (used only when compiling idyntree from source)
libxml2 = "*"
assimp = "*"
ipopt = "*"
# Used to download and build dependencies from source
colcon-common-extensions = "*"
vcstool = "*"
