export CMAKE_INSTALL_PREFIX=$CONDA_PREFIX
export CMAKE_PREFIX_PATH=$CMAKE_INSTALL_PREFIX:$CMAKE_PREFIX_PATH
export PYTHONPATH=
export YARP_DATA_DIRS=$CMAKE_INSTALL_PREFIX/share/yarp:$CMAKE_INSTALL_PREFIX/share/ergoCub
