name: CI Workflow

on:
  pull_request:

jobs:
  build-with-pixi:
    name: '[pixi:${{ matrix.os }}]'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        os: [ubuntu-22.04, macos-latest, windows-2019]

    steps:
    - uses: actions/checkout@v4

    - name: Print used environment
      shell: bash
      run: |
        env

    - uses: prefix-dev/setup-pixi@v0.5.1

    - name: Run the tests
      shell: bash -l {0}
      run: |
        pixi run download_deps
        pixi run install_deps
        pixi run test
